### ISSUE TITLE
undefined method `find_with_parents' using trunk

### ISSUE THREAD

**Issue by heyudude** [hron/redmine_subtasks#10]
With the latest trunk I get the following error when selecting the roadmap tab:
/usr/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/base.rb:1833:in `method_missing'
vendor/plugins/redmine_subtasks/app/views/projects/roadmap.rhtml:18
vendor/plugins/redmine_subtasks/app/views/projects/roadmap.rhtml:7:in`each'
vendor/plugins/redmine_subtasks/app/views/projects/roadmap.rhtml:7

**Comment by hron** [comment]
I have deleted that method long time ago. 17 Jule 2009. Here is the commit:
http://github.com/hron/redmine_subtasks/commit/6abdd55e4f212a7ea75d909dd490d96440cdc874

I think you use not latest code of the plugin.

**Comment by heyudude** [comment]
Sorry for that: I did a git clone yesterday, not sure what went wrong.

I did a "git pull" and the commit was applied:
<code>
Updating 1d44c04..bfcac35
Fast forward
 app/views/projects/roadmap.rhtml                   |    6 ++++--
 config/locales/es.yml                              |   17 +++++++++
 config/locales/pt.yml                              |   17 +++++++++
 lib/redmine_subtasks/redmine_ext/issue_patch.rb    |    2 +-
 .../redmine_ext/versions_helper_patch.rb           |    2 +-
</code>

**Comment by hron** [comment]
No problem!

Let me know if there is any problem and I will try to help your. Thank you for use my plugin and bugreports. ;]

BTW, I have modified this plugin to start in the stable version of Redmine yesterday, but I am still not sure that everything works good.

**Comment by heyudude** [comment]
Ok, the stable version would be great. I really like your setup.

I will test it with a copy of our production environment when available.

**Comment by heyudude** [comment]
Any updates on the progress on the Stable version yet?
