### ISSUE TITLE
Error 500 when tryin to view an issue.Another one

### ISSUE THREAD

**Issue by eniwetok** [hron/redmine_subtasks#12]
Processing IssuesController#show (for 172.16.7.50 at 2009-11-11 12:08:22) [GET]
  Parameters: {"action"=>"show", "id"=>"3728", "controller"=>"issues"}
Rendering template within layouts/base
Rendering issues/show.rhtml

ActionView::TemplateError (undefined method `project' for nil:NilClass) on line #4 of app/views/issues/_changesets.rhtml:
1: <% changesets.each do |changeset| %>
2:     <div class="changeset <%= cycle('odd', 'even') %>">
3:     <p><%= link_to("#{l(:label_revision)} #{changeset.revision}",
4:                 :controller => 'repositories', :action => 'revision', :id => changeset.project, :rev => changeset.revision) %><br />
5:         <span class="author"><%= authoring(changeset.committed_on, changeset.author) %></span></p>
6:     <%= textilizable(changeset, :comments) %>
7:     </div>

```
app/models/changeset.rb:58:in `project'
app/views/issues/_changesets.rhtml:4:in `_run_rhtml_app47views47issues47_changesets46rhtml_locals_changesets_object'
app/views/issues/_changesets.rhtml:1:in `_run_rhtml_app47views47issues47_changesets46rhtml_locals_changesets_object'
vendor/plugins/redmine_subtasks/app/views/issues/show.rhtml:104:in `_run_rhtml_vendor47plugins47redmine_subtasks47app47views47issues47show46rhtml'
vendor/plugins/redmine_subtasks/app/controllers/issues_controller.rb:131:in `show'
vendor/plugins/redmine_subtasks/app/controllers/issues_controller.rb:129:in `show'
```

Rendering /etc/www/redmine/public/500.html (500 Internal Server Error)

Processing IssuesController#show (for 172.16.7.50 at 2009-11-11 12:08:25) [GET]
  Parameters: {"action"=>"show", "id"=>"3571", "controller"=>"issues"}
Rendering template within layouts/base
Rendering issues/show.rhtml
Completed in 2979ms (View: 2518, DB: 44) | 200 OK [http://intranet/issues/3571]

**Comment by yalovali** [comment]
+1
