### ISSUE TITLE
RuntimeError in Issues#index 

### ISSUE THREAD

**Issue by kvrnkiran** [hron/redmine_subtasks#13]
Hi,

I have installed the latest redMine (from trunk) and copied latest version of subtasks to plugins folder.  After that, I ran rake to migrate all plugins also.

Whenever I click on the link - Issues, I get the following error -

 RuntimeError in Issues#index

Showing vendor/plugins/hron-redmine_subtasks-bfcac35/app/views/issues/index.rhtml where line #2 raised:

No plugin called 'redmine_subtasks' - please use the full name of a loaded plugin.

Extracted source (around line #2):

1: <% content_for :header_tags do %>
2:   <%= stylesheet_link_tag 'stylesheet', :plugin => 'redmine_subtasks' %>
3: <% end %>
4: 
5: <% if @query.new_record? %>

RAILS_ROOT: /home/kirakvrn/rmtrunk

Full Trace:

home/kirakvrn/rmtrunk/vendor/plugins/engines/lib/engines/rails_extensions/asset_helpers.rb:111:in `plugin_asset_path'
/home/kirakvrn/rmtrunk/vendor/plugins/engines/lib/engines/rails_extensions/asset_helpers.rb:104:in`pluginify_sources'
/home/kirakvrn/rmtrunk/vendor/plugins/engines/lib/engines/rails_extensions/asset_helpers.rb:104:in `map!'
/home/kirakvrn/rmtrunk/vendor/plugins/engines/lib/engines/rails_extensions/asset_helpers.rb:104:in`pluginify_sources'
/home/kirakvrn/rmtrunk/vendor/plugins/engines/lib/engines/rails_extensions/asset_helpers.rb:67:in `stylesheet_link_tag'
/home/kirakvrn/rmtrunk/vendor/plugins/hron-redmine_subtasks-bfcac35/app/views/issues/index.rhtml:2:in`_run_rhtml_vendor47plugins47hron45redmine_subtasks45bfcac3547app47views47issues47index46rhtml'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_view/helpers/capture_helper.rb:36:in `call'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_view/helpers/capture_helper.rb:36:in`capture'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_view/helpers/capture_helper.rb:129:in `with_output_buffer'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_view/helpers/capture_helper.rb:36:in`capture'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_view/helpers/capture_helper.rb:120:in `content_for'
/home/kirakvrn/rmtrunk/app/helpers/application_helper.rb:663:in`content_for'
/home/kirakvrn/rmtrunk/vendor/plugins/hron-redmine_subtasks-bfcac35/app/views/issues/index.rhtml:1:in `_run_rhtml_vendor47plugins47hron45redmine_subtasks45bfcac3547app47views47issues47index46rhtml'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_view/renderable.rb:34:in`send'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_view/renderable.rb:34:in `render'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_view/base.rb:301:in`with_template'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_view/renderable.rb:30:in `render'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_view/template.rb:199:in`render_template'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_view/base.rb:260:in `render'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_view/base.rb:343:in`_render_with_layout'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_view/base.rb:257:in `render'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/base.rb:1250:in`render_for_file'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/base.rb:945:in `render_without_benchmark'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/benchmarking.rb:51:in`render'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/usr/lib/ruby/1.8/benchmark.rb:308:in`realtime'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/benchmarking.rb:51:in`render'
/home/kirakvrn/rmtrunk/app/controllers/issues_controller.rb:82:in `index'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/mime_responds.rb:135:in`call'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/mime_responds.rb:135:in `custom'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/mime_responds.rb:179:in`call'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/mime_responds.rb:179:in `respond'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/mime_responds.rb:173:in`each'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/mime_responds.rb:173:in `respond'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/mime_responds.rb:107:in`respond_to'
/home/kirakvrn/rmtrunk/app/controllers/issues_controller.rb:71:in `index'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/base.rb:1331:in`send'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/base.rb:1331:in `perform_action_without_filters'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/filters.rb:617:in`call_filters'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/filters.rb:610:in `perform_action_without_benchmark'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/benchmarking.rb:68:in`perform_action_without_rescue'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/usr/lib/ruby/1.8/benchmark.rb:308:in`realtime'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/benchmarking.rb:68:in`perform_action_without_rescue'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/rescue.rb:160:in `perform_action_without_flash'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/flash.rb:146:in`perform_action'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/base.rb:532:in `send'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/base.rb:532:in`process_without_filters'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/filters.rb:606:in `process'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/base.rb:391:in`process'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/base.rb:386:in `call'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/routing/route_set.rb:437:in`call'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/dispatcher.rb:87:in `dispatch'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/dispatcher.rb:121:in`_call'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/dispatcher.rb:130:in `build_middleware_stack'
/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.4/lib/active_record/query_cache.rb:29:in`call'
/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.4/lib/active_record/query_cache.rb:29:in `call'
/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.4/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in`cache'
/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.4/lib/active_record/query_cache.rb:9:in `cache'
/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.4/lib/active_record/query_cache.rb:28:in`call'
/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
/usr/lib/ruby/gems/1.8/gems/rack-1.0.0/lib/rack/head.rb:9:in`call'
/usr/lib/ruby/gems/1.8/gems/rack-1.0.0/lib/rack/methodoverride.rb:24:in `call'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/params_parser.rb:15:in`call'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/session/cookie_store.rb:93:in `call'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/failsafe.rb:26:in`call'
/usr/lib/ruby/gems/1.8/gems/rack-1.0.0/lib/rack/lock.rb:11:in `call'
/usr/lib/ruby/gems/1.8/gems/rack-1.0.0/lib/rack/lock.rb:11:in`synchronize'
/usr/lib/ruby/gems/1.8/gems/rack-1.0.0/lib/rack/lock.rb:11:in `call'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/dispatcher.rb:114:in`call'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/reloader.rb:34:in `run'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/dispatcher.rb:108:in`call'
/usr/lib/ruby/gems/1.8/gems/rack-1.0.0/lib/rack/content_length.rb:13:in `call'
/usr/lib/ruby/gems/1.8/gems/rack-1.0.0/lib/rack/handler/fastcgi.rb:56:in`serve'
/usr/lib/ruby/gems/1.8/gems/rails-2.3.4/lib/fcgi_handler.rb:103:in `process_request'
/usr/lib/ruby/gems/1.8/gems/rails-2.3.4/lib/fcgi_handler.rb:153:in`with_signal_handler'
/usr/lib/ruby/gems/1.8/gems/rails-2.3.4/lib/fcgi_handler.rb:101:in `process_request'
/usr/lib/ruby/gems/1.8/gems/rails-2.3.4/lib/fcgi_handler.rb:78:in`process_each_request'
/usr/lib/ruby/gems/1.8/gems/rails-2.3.4/lib/fcgi_handler.rb:77:in `each'
/usr/lib/ruby/gems/1.8/gems/rails-2.3.4/lib/fcgi_handler.rb:77:in`process_each_request'
/usr/lib/ruby/gems/1.8/gems/rails-2.3.4/lib/fcgi_handler.rb:76:in `catch'
/usr/lib/ruby/gems/1.8/gems/rails-2.3.4/lib/fcgi_handler.rb:76:in`process_each_request'
/usr/lib/ruby/gems/1.8/gems/rails-2.3.4/lib/fcgi_handler.rb:51:in `process!'
/usr/lib/ruby/gems/1.8/gems/rails-2.3.4/lib/fcgi_handler.rb:23:in`process!'
dispatch.fcgi:24

Can you please let me know what am I missing?  

Thanks in advance,
Kiran

**Comment by kvrnkiran** [comment]
Hi,

Sorry, I realized the problem.  I set the folder name to correct name in plugins directory and everything is fine.

I really like this plugin.  Thanks a bunch.

Kiran.

**Comment by armando82** [comment]
Hi Kiran,

Would you mind telling me what's the correct folder name?? I have the same problem but I haven't found it yet.

Thanks in advance,
Armando

**Comment by armando82** [comment]
I found it. The folder is supposed to be named redmine_subtasks.

Thanks anyway
