### ISSUE TITLE
Show Parents options cannot be saved

### ISSUE THREAD

**Issue by kvrnkiran** [hron/redmine_subtasks#14]
Hi,

This is a wonderful plugin that I love to use.

But, I am having a problem that, whenever I see the list of issues in redmine, I see the Show Parents combo box always shows Never.  There is no way of saving this option, so that, I can always have Organize by parent selected.

Any help is greatly appreciated.

Kiran.

**Comment by hron** [comment]
This configuration saves just as other filter rules: redmine keeps it in the session, and you can "Save" filters, "Show Parents" should saves too.

**Comment by kvrnkiran** [comment]
Thank you very much for the quick reply.  Unfortunately, my redmine is not saving Show Parents.  (please have a look at the screen shot: http://www.kvrnkiran.in/redmine.PNG ).  I am using the trunk version of redmine and 0.0.1 version of Subtasks plugin.

Thanks in advance.

**Comment by hron** [comment]
Probably something changes in the time between redmine_subtasks was developed and current Redmine trunk. Unfortunately, I have no time to test/fix that now. ;(
