### ISSUE TITLE
Installation fails while migration db

### ISSUE THREAD

**Issue by chnoack** [hron/redmine_subtasks#16]
My setup: Ruby Enterprise Linux 1.8.7, redmine 0.8.7 stable, sqlite3

After copying redmine_subtasks to the vendor/plugin folder I tried to migrate the db. First I was asked to install awesome_nested_set.

<pre>
christian$ sudo gem install awesome_nested_set
Successfully installed awesome_nested_set-1.4.3
...
</pre>

The I ran the migration again and go this error:

<pre>
christian$ sudo rake --trace  RAILS_ENV=production db:migrate_plugins
(in /Library/WebServer/SecureDocuments/agile-methods.eu/redmineThomasChristian-0.8.0)
** Invoke db:migrate_plugins (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
undefined method `map' for nil:NilClass
/opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/site_ruby/1.8/rubygems.rb:270:in `activate'
/opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/site_ruby/1.8/rubygems.rb:296:in `activate'
/opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/site_ruby/1.8/rubygems.rb:295:in `each'
/opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/site_ruby/1.8/rubygems.rb:295:in `activate'
/opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:35:in `require'
/Library/WebServer/SecureDocuments/agile-methods.eu/redmineThomasChristian-0.8.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
/Library/WebServer/SecureDocuments/agile-methods.eu/redmineThomasChristian-0.8.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:355:in `new_constants_in'
/Library/WebServer/SecureDocuments/agile-methods.eu/redmineThomasChristian-0.8.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
/Library/WebServer/SecureDocuments/agile-methods.eu/redmineThomasChristian-0.8.0/vendor/plugins/redmine_subtasks/lib/redmine_subtasks/redmine_ext/awesome_nested_set_patch.rb:1
/opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
/Library/WebServer/SecureDocuments/agile-methods.eu/redmineThomasChristian-0.8.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
/Library/WebServer/SecureDocuments/agile-methods.eu/redmineThomasChristian-0.8.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:355:in `new_constants_in'
/Library/WebServer/SecureDocuments/agile-methods.eu/redmineThomasChristian-0.8.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
/Library/WebServer/SecureDocuments/agile-methods.eu/redmineThomasChristian-0.8.0/vendor/plugins/redmine_subtasks/lib/redmine_subtasks/redmine_ext/issue_patch.rb:1
/opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
</pre>

Any hints? Best regards,

Christian

**Comment by hron** [comment]
This plugin works _only_ on Redmine 0.9 version.
