### ISSUE TITLE
subtasks with advanced roadmap

### ISSUE THREAD

**Issue by Marco83** [hron/redmine_subtasks#18]
hello,

thanks for your advices from last post, everything is running fine.

I tried to install another plugin "advanced roadmap" but if this plugin is installed the subtask plugin doesn't work (the "create subb issue" button isn't availabe and the view of child and parent doesn't show the hirachy.

Does anybody has installed both plugins with success?

**Comment by hron** [comment]
I think both of these plugin try to override the same template or partial. This can be resolved only if the developers of Redmine introduce a hook for the part both plugins needs.
