### ISSUE TITLE
incorrect parent task progress calculation

### ISSUE THREAD

**Issue by brodock** [hron/redmine_subtasks#2]
If you change progress for a sub-issue and then add another one, the parent task will not recalculate progress based on both's progress (and the estimated time needed to complete)

**Comment by hron** [comment]
These values calculates every time you see the parent issue. I can't duplicate this.

**Comment by nwp90** [comment]
FWIW I found the method used to calculate parent progress (based purely on dates) to bear no relation to reality - I replaced it with something that seems (to me at least) to make much more sense, based on estimated time and logged time. I've put the version with my fixes up at http://github.com/nwp90/redmine_subtasks -- Aleksei, feel free to help yourself as you wish.

**Comment by nwp90** [comment]
I see someone else has done similar too - http://github.com/zigzag/redmine_subtasks/commit/dcfdc25659fd33940947f94bebc91f1ba143dfe2
