### ISSUE TITLE
Cannot install plugin: Error during db:migrate

### ISSUE THREAD

**Issue by mariocasciaro** [hron/redmine_subtasks#3]
<code>
sudo rake db:migrate_plugins RAILS_ENV="production" --trace
(in /opt/redmine)
*\* Invoke db:migrate_plugins (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
undefined method `create_journal' for class`Issue'
/opt/redmine/vendor/rails/activesupport/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method'
/opt/redmine/vendor/rails/activesupport/lib/active_support/core_ext/module/aliasing.rb:31:in`alias_method_chain'
/opt/redmine/vendor/plugins/hron-subtasks/lib/redmine_subtasks/redmine_ext/issue_patch.rb:137:in `included'
/opt/redmine/vendor/plugins/hron-subtasks/lib/redmine_subtasks/redmine_ext/issue_patch.rb:8:in`class_eval'
/opt/redmine/vendor/plugins/hron-subtasks/lib/redmine_subtasks/redmine_ext/issue_patch.rb:8:in `included'
/opt/redmine/vendor/plugins/hron-subtasks/init.rb:42:in`include'
/opt/redmine/vendor/plugins/hron-subtasks/init.rb:42:in `send'
/opt/redmine/vendor/plugins/hron-subtasks/init.rb:42:in`evaluate_init_rb'
/opt/redmine/vendor/rails/activesupport/lib/active_support/callbacks.rb:177:in `call'
/opt/redmine/vendor/rails/activesupport/lib/active_support/callbacks.rb:177:in`evaluate_method'
/opt/redmine/vendor/rails/activesupport/lib/active_support/callbacks.rb:161:in `call'
/opt/redmine/vendor/rails/activesupport/lib/active_support/callbacks.rb:90:in`run'
/opt/redmine/vendor/rails/activesupport/lib/active_support/callbacks.rb:90:in `each'
/opt/redmine/vendor/rails/activesupport/lib/active_support/callbacks.rb:90:in`send'
/opt/redmine/vendor/rails/activesupport/lib/active_support/callbacks.rb:90:in `run'
/opt/redmine/vendor/rails/activesupport/lib/active_support/callbacks.rb:272:in`run_callbacks'
/opt/redmine/vendor/rails/railties/lib/initializer.rb:493:in `send'
/opt/redmine/vendor/rails/railties/lib/initializer.rb:493:in`prepare_dispatcher'
/opt/redmine/vendor/rails/railties/lib/initializer.rb:155:in `process'
/opt/redmine/vendor/rails/railties/lib/initializer.rb:97:in`send'
/opt/redmine/vendor/rails/railties/lib/initializer.rb:97:in `run'
/opt/redmine/config/environment.rb:20
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
/opt/redmine/vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in`require'
/opt/redmine/vendor/rails/activesupport/lib/active_support/dependencies.rb:355:in `new_constants_in'
/opt/redmine/vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in`require'
/opt/redmine/vendor/rails/railties/lib/tasks/misc.rake:3
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`execute'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in`execute'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:607:in`invoke_prerequisites'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:604:in `each'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:604:in`invoke_prerequisites'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:596:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in`invoke'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in`top_level'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
/var/lib/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/var/lib/gems/1.8/gems/rake-0.8.7/bin/rake:31
/var/lib/gems/1.8/bin//rake:19:in`load'
/var/lib/gems/1.8/bin//rake:19
<code>

**Comment by hron** [comment]
The plugin does not work with 0.8.2 version of Redmine. This problem related to using stable version. You have to use trunk version to use this plugin.

**Comment by telepenin** [comment]
Good day. The same error in versions 0.8 and 0.8.4. Which version works? And how soon will plugin for redmine 0.8.4?

**Comment by hron** [comment]
Trunk version, future 0.9. I do not know when this plugin will work with 0.8.4.
