### ISSUE TITLE
Error while installing plugin

### ISSUE THREAD

**Issue by grinka** [hron/redmine_subtasks#4]
here is a trace:

<pre>
** Execute environment
rake aborted!
no such file to load -- awesome_nested_set
D:/tools/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
D:/tools/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
D:/Development/redmine-0.8.4/vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
D:/Development/redmine-0.8.4/vendor/rails/activesupport/lib/active_support/dependencies.rb:355:in `new_constants_in'
D:/Development/redmine-0.8.4/vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
D:/Development/redmine-0.8.4/vendor/plugins/redmine_subtasks/lib/redmine_subtasks/redmine_ext/awesome_nested_set_patch.rb:1
D:/tools/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
D:/tools/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
D:/Development/redmine-0.8.4/vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
D:/Development/redmine-0.8.4/vendor/rails/activesupport/lib/active_support/dependencies.rb:355:in `new_constants_in'
D:/Development/redmine-0.8.4/vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
D:/Development/redmine-0.8.4/vendor/plugins/redmine_subtasks/lib/redmine_subtasks/redmine_ext/issue_patch.rb:1
D:/tools/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
D:/tools/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
D:/Development/redmine-0.8.4/vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
D:/Development/redmine-0.8.4/vendor/rails/activesupport/lib/active_support/dependencies.rb:355:in `new_constants_in'
D:/Development/redmine-0.8.4/vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
D:/Development/redmine-0.8.4/vendor/plugins/redmine_subtasks/lib/redmine_subtasks/redmine_ext.rb:1
D:/tools/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
D:/tools/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
D:/Development/redmine-0.8.4/vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
D:/Development/redmine-0.8.4/vendor/rails/activesupport/lib/active_support/dependencies.rb:355:in `new_constants_in'
D:/Development/redmine-0.8.4/vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
D:/Development/redmine-0.8.4/vendor/plugins/redmine_subtasks/init.rb:6:in `evaluate_init_rb'
D:/Development/redmine-0.8.4/vendor/rails/railties/lib/rails/plugin.rb:95:in `evaluate_init_rb'
D:/Development/redmine-0.8.4/vendor/rails/activesupport/lib/active_support/core_ext/kernel/reporting.rb:11:in `silence_warnings'
D:/Development/redmine-0.8.4/vendor/rails/railties/lib/rails/plugin.rb:91:in `evaluate_init_rb'
D:/Development/redmine-0.8.4/vendor/rails/railties/lib/rails/plugin.rb:44:in `load'
D:/Development/redmine-0.8.4/config/../vendor/plugins/engines/lib/engines/plugin.rb:77:in `load'
D:/Development/redmine-0.8.4/vendor/rails/railties/lib/rails/plugin/loader.rb:33:in `load_plugins'
D:/Development/redmine-0.8.4/vendor/rails/railties/lib/rails/plugin/loader.rb:32:in `each'
D:/Development/redmine-0.8.4/vendor/rails/railties/lib/rails/plugin/loader.rb:32:in `load_plugins'
D:/Development/redmine-0.8.4/vendor/rails/railties/lib/initializer.rb:292:in `load_plugins'
D:/Development/redmine-0.8.4/vendor/rails/railties/lib/initializer.rb:142:in `process'
D:/Development/redmine-0.8.4/vendor/rails/railties/lib/initializer.rb:97:in `send'
D:/Development/redmine-0.8.4/vendor/rails/railties/lib/initializer.rb:97:in `run'
D:/Development/redmine-0.8.4/config/environment.rb:20
D:/tools/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
D:/tools/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
D:/Development/redmine-0.8.4/vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
D:/Development/redmine-0.8.4/vendor/rails/activesupport/lib/active_support/dependencies.rb:355:in `new_constants_in'
D:/Development/redmine-0.8.4/vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
D:/Development/redmine-0.8.4/vendor/rails/railties/lib/tasks/misc.rake:3
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:546:in `call'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:546:in `execute'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:541:in `each'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:541:in `execute'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:508:in `invoke_with_call_chain'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:501:in `synchronize'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:501:in `invoke_with_call_chain'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:518:in `invoke_prerequisites'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1183:in `each'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1183:in `send'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1183:in `each'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:515:in `invoke_prerequisites'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:507:in `invoke_with_call_chain'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:501:in `synchronize'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:501:in `invoke_with_call_chain'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:494:in `invoke'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1931:in `invoke_task'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1909:in `top_level'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1909:in `each'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1909:in `top_level'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1948:in `standard_exception_handling'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1903:in `top_level'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1881:in `run'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1948:in `standard_exception_handling'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1878:in `run'
D:/tools/Ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/bin/rake:31
D:/tools/Ruby/bin/rake:19:in `load'
D:/tools/Ruby/bin/rake:19
</pre>

**Comment by nviau** [comment]
I had the same problem, it seems you need to checkout the trunk of Redmine, which includes awesome_nested_set. I am however still having problems with the plugin, I'll post separately.

**Comment by anepomnyaschih** [comment]
The same error :(

**Comment by hron** [comment]
This plugin works only with trunk version of Redmine.

**Comment by anepomnyaschih** [comment]
Aleksei, could you, please, make branch for stable version of Redmine (0.8.x)? I think, people is not ready to use trunk version, because it is unstable. I hope, it will need a bit of your time to corrent the plugin correspondingly to 0.8.x functionality. It would be very useful.

**Comment by sub** [comment]
I'm having the same problem as I use redmine last stable release (0.8.4). I can't use the trunk snapshot, I need a stable enviroment in a production system. 
A porting would be really appreciated...

**Comment by jwisener** [comment]
I'm running Redmine 0.8.7.stable version. I'm scared to try and install this plugin. do you think it will work or will I have the same issues.

**Comment by hron** [comment]
No, the plugin works only on trunk version (future 0.9).
