### ISSUE TITLE
rake db:migrate_plugins can't find Issue.create_journal

### ISSUE THREAD

**Issue by anepomnyaschih** [hron/redmine_subtasks#7]
I use redmine 0.8.4 bitnami stack. I get following error installing the plugin:

<pre>
bash-3.2# RAILS_ENV="production" rake --trace db:migrate_plugins
(in /opt/redmine-0.8.4-0/apps/redmine)
** Invoke db:migrate_plugins (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
undefined method `create_journal' for class `Issue'
/opt/redmine-0.8.4-0/apps/redmine/vendor/rails/activesupport/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method'
/opt/redmine-0.8.4-0/apps/redmine/vendor/rails/activesupport/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method_chain'
/opt/redmine-0.8.4-0/apps/redmine/vendor/plugins/redmine_subtasks/lib/redmine_subtasks/redmine_ext/issue_patch.rb:137:in `included'
/opt/redmine-0.8.4-0/apps/redmine/vendor/plugins/redmine_subtasks/lib/redmine_subtasks/redmine_ext/issue_patch.rb:8:in `class_eval'
/opt/redmine-0.8.4-0/apps/redmine/vendor/plugins/redmine_subtasks/lib/redmine_subtasks/redmine_ext/issue_patch.rb:8:in `included'
/opt/redmine-0.8.4-0/apps/redmine/vendor/plugins/redmine_subtasks/init.rb:42:in `include'
/opt/redmine-0.8.4-0/apps/redmine/vendor/plugins/redmine_subtasks/init.rb:42:in `send'
/opt/redmine-0.8.4-0/apps/redmine/vendor/plugins/redmine_subtasks/init.rb:42:in `evaluate_init_rb'
/opt/redmine-0.8.4-0/apps/redmine/vendor/rails/activesupport/lib/active_support/callbacks.rb:177:in `call'
/opt/redmine-0.8.4-0/apps/redmine/vendor/rails/activesupport/lib/active_support/callbacks.rb:177:in `evaluate_method'
/opt/redmine-0.8.4-0/apps/redmine/vendor/rails/activesupport/lib/active_support/callbacks.rb:161:in `call'
/opt/redmine-0.8.4-0/apps/redmine/vendor/rails/activesupport/lib/active_support/callbacks.rb:90:in `run'
/opt/redmine-0.8.4-0/apps/redmine/vendor/rails/activesupport/lib/active_support/callbacks.rb:90:in `each'
/opt/redmine-0.8.4-0/apps/redmine/vendor/rails/activesupport/lib/active_support/callbacks.rb:90:in `send'
/opt/redmine-0.8.4-0/apps/redmine/vendor/rails/activesupport/lib/active_support/callbacks.rb:90:in `run'
/opt/redmine-0.8.4-0/apps/redmine/vendor/rails/activesupport/lib/active_support/callbacks.rb:272:in `run_callbacks'
/opt/redmine-0.8.4-0/apps/redmine/vendor/rails/railties/lib/initializer.rb:493:in `send'
/opt/redmine-0.8.4-0/apps/redmine/vendor/rails/railties/lib/initializer.rb:493:in `prepare_dispatcher'
/opt/redmine-0.8.4-0/apps/redmine/vendor/rails/railties/lib/initializer.rb:155:in `process'
/opt/redmine-0.8.4-0/apps/redmine/vendor/rails/railties/lib/initializer.rb:97:in `send'
/opt/redmine-0.8.4-0/apps/redmine/vendor/rails/railties/lib/initializer.rb:97:in `run'
/opt/redmine-0.8.4-0/apps/redmine/config/environment.rb:20
/opt/redmine-0.8.4-0/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:27:in `gem_original_require'
/opt/redmine-0.8.4-0/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:27:in `require'
/opt/redmine-0.8.4-0/apps/redmine/vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
/opt/redmine-0.8.4-0/apps/redmine/vendor/rails/activesupport/lib/active_support/dependencies.rb:355:in `new_constants_in'
/opt/redmine-0.8.4-0/apps/redmine/vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
/opt/redmine-0.8.4-0/apps/redmine/vendor/rails/railties/lib/tasks/misc.rake:3
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:546:in `call'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:546:in `execute'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:541:in `each'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:541:in `execute'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:508:in `invoke_with_call_chain'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:501:in `synchronize'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:501:in `invoke_with_call_chain'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:518:in `invoke_prerequisites'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1183:in `each'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1183:in `send'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1183:in `each'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:515:in `invoke_prerequisites'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:507:in `invoke_with_call_chain'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:501:in `synchronize'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:501:in `invoke_with_call_chain'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:494:in `invoke'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1931:in `invoke_task'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1909:in `top_level'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1909:in `each'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1909:in `top_level'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1948:in `standard_exception_handling'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1903:in `top_level'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1881:in `run'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1948:in `standard_exception_handling'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/lib/rake.rb:1878:in `run'
/opt/redmine-0.8.4-0/ruby/lib/ruby/gems/1.8/gems/rake-0.8.1/bin/rake:31
/opt/redmine-0.8.4-0/ruby/bin/rake:19:in `load'
/opt/redmine-0.8.4-0/ruby/bin/rake:19
bash-3.2#
</pre>

Does it mean, that the plugin is not compatible with redmine 0.8.4?

**Comment by hron** [comment]
This plugin works only with trunk version of Redmine.
