### ISSUE TITLE
Estimated hours not updated when running on redmine 'trunk'

### ISSUE THREAD

**Issue by thorin** [hron/redmine_subtasks#8]
When running the redmine trunk with rails 2.2.2 and redmine_subtasks the estimated_hours field was not being updated.

I managed to fix it with the following patch:

<pre>
 diff -r redmine_subtasks/lib/redmine_subtasks/redmine_ext/issue_patch.rb redmine_subtasks_fixed/lib/redmine_subtasks/redmine_ext/issue_patch.rb
 241,242c241,242
 <           def estimated_hours_with_subtasks=( h)
 <             estimated_hours_without_subtasks=( h) if leaf?
 \-\-\-
 >           def estimated_hours_with_subtasks=(h)
 >             self.estimated_hours_without_subtasks=(h) if leaf?
</pre>

Hope this helps.

Ricardo

**Comment by hron** [comment]
The patch works good. Thanks!
