### ISSUE TITLE
undefined method `create_journal' for class `Issue'  

### ISSUE THREAD

**Issue by heyudude** [hron/redmine_subtasks#9]
I get a:
undefined method `create_journal' for class`Issue'

Redmine 0.8.3 when issuing rake db:migrate_plugins

**Comment by hron** [comment]
This plugin compatible with trunk version of Redmine.

**Comment by hron** [comment]
I mean _only_ with trunk version, not with the current stable (0.8.x).

**Comment by singalen** [comment]
Is there a way to quickly hack it to work with, say, 0.8.7?
Thanks.
